>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()

Test valid integers:
>>> bg.integer_validator("my_int", 12)
>>> bg.integer_validator("width", 89)
>>> bg.integer_validator("height", 1)

Test area method:
>>> bg.area()
Traceback (most recent call last):
    ...
Exception: area() is not implemented

Test string instead of integer:
>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
    ...
TypeError: name must be an integer

Test zero:
>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
    ...
ValueError: age must be greater than 0

Test negative number:
>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
    ...
ValueError: distance must be greater than 0

Test float:
>>> bg.integer_validator("height", 1.5)
Traceback (most recent call last):
    ...
TypeError: height must be an integer

Test boolean:
>>> bg.integer_validator("flag", True)
Traceback (most recent call last):
    ...
TypeError: flag must be an integer

>>> bg.integer_validator("flag", False)
Traceback (most recent call last):
    ...
TypeError: flag must be an integer

Test None:
>>> bg.integer_validator("value", None)
Traceback (most recent call last):
    ...
TypeError: value must be an integer

Test list:
>>> bg.integer_validator("my_list", [1, 2, 3])
Traceback (most recent call last):
    ...
TypeError: my_list must be an integer

Test tuple:
>>> bg.integer_validator("my_tuple", (1, 2))
Traceback (most recent call last):
    ...
TypeError: my_tuple must be an integer

Test dict:
>>> bg.integer_validator("my_dict", {"key": "value"})
Traceback (most recent call last):
    ...
TypeError: my_dict must be an integer

Test set:
>>> bg.integer_validator("my_set", {1, 2, 3})
Traceback (most recent call last):
    ...
TypeError: my_set must be an integer

Test missing arguments:
>>> bg.integer_validator("test")
Traceback (most recent call last):
    ...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator()
Traceback (most recent call last):
    ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test too many arguments:
>>> bg.integer_validator("test", 1, 2)
Traceback (most recent call last):
    ...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

Test area with arguments:
>>> bg.area(1)
Traceback (most recent call last):
    ...
TypeError: area() takes 1 positional argument but 2 were given
